// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddqailhqsxbuhvyxuxfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkcWFpbGhxc3hidWh2eXh1eGZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3Njg1NTMsImV4cCI6MjA3NDM0NDU1M30.NJAi7Psxt5ASy4_X5NdBOueP45OmK_tyueOig6zfHX8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});